- name: ap-cp-happy
  duration: 300s
  repetitions: 1
  parallel: true
  fail_fast: false
  loadgenerator_count: 2
  node_count: 0
  driver: hazelcast5
  version: maven=5.7.0
  client_hazelcast_xml: client-hazelcast.xml
  loadgenerator_hosts: loadgenerators
  node_hosts: nodes
  member_hosts: hazelcast
  verify_enabled: true
  performance_monitor_interval_seconds: 1
  warmup_seconds: 30
  cooldown_seconds: 20
  test:
      - name: ap-map-happy
        class: com.hazelcast.simulator.tests.map.StringStringMapTest
        threadCount: 20
        getProb: 0.66
        putProb: 0.34
        keyCount: 10000
        keyLength: 32
        minValueLength: 256
        maxValueLength: 256
        ratePerSecond: 40
      - name: cp-map-happy
        class: com.hazelcast.simulator.tests.cp.CPMapTest
        threadCount: 20
        cpGroups: 5
        maps: 5
        keys: 2000
        valuesCount: 100
        getProb: 0.66
        setProb: 0.34
        putProb: 0
        putIfAbsentProb: 0
        casProb: 0
        removeProb: 0
        deleteProb: 0
        valueSizeBytes: 256
        ratePerSecond: 40

- name: ap-cp-region-c-pod-failure
  duration: 300s
  repetitions: 1
  parallel: true
  fail_fast: false
  loadgenerator_count: 2
  node_count: 0
  driver: hazelcast5
  version: maven=5.7.0
  client_hazelcast_xml: client-hazelcast.xml
  loadgenerator_hosts: loadgenerators
  node_hosts: nodes
  member_hosts: hazelcast
  verify_enabled: true
  performance_monitor_interval_seconds: 1
  warmup_seconds: 30
  cooldown_seconds: 20
  test:
      - name: ap-map-pod-failure
        class: com.hazelcast.simulator.tests.map.StringStringMapTest
        threadCount: 20
        getProb: 0.66
        putProb: 0.34
        keyCount: 10000
        keyLength: 32
        minValueLength: 256
        maxValueLength: 256
        ratePerSecond: 40
      - name: cp-map-pod-failure
        class: com.hazelcast.simulator.tests.cp.CPMapTest
        threadCount: 20
        cpGroups: 5
        maps: 5
        keys: 2000
        valuesCount: 100
        getProb: 0.66
        setProb: 0.34
        putProb: 0
        putIfAbsentProb: 0
        casProb: 0
        removeProb: 0
        deleteProb: 0
        valueSizeBytes: 256
        ratePerSecond: 40

- name: ap-cp-region-c-network-isolation
  duration: 300s
  repetitions: 1
  parallel: true
  fail_fast: false
  loadgenerator_count: 2
  node_count: 0
  driver: hazelcast5
  version: maven=5.7.0
  client_hazelcast_xml: client-hazelcast.xml
  loadgenerator_hosts: loadgenerators
  node_hosts: nodes
  member_hosts: hazelcast
  verify_enabled: true
  performance_monitor_interval_seconds: 1
  warmup_seconds: 30
  cooldown_seconds: 20
  test:
      - name: ap-map-network-isolation
        class: com.hazelcast.simulator.tests.map.StringStringMapTest
        threadCount: 20
        getProb: 0.66
        putProb: 0.34
        keyCount: 10000
        keyLength: 32
        minValueLength: 256
        maxValueLength: 256
        ratePerSecond: 40
      - name: cp-map-network-isolation
        class: com.hazelcast.simulator.tests.cp.CPMapTest
        threadCount: 20
        cpGroups: 5
        maps: 5
        keys: 2000
        valuesCount: 100
        getProb: 0.66
        setProb: 0.34
        putProb: 0
        putIfAbsentProb: 0
        casProb: 0
        removeProb: 0
        deleteProb: 0
        valueSizeBytes: 256
        ratePerSecond: 40
